version: '3.8'

services:
  server:
    image: opensign/opensignserver:main
    container_name: OpenSignServer-container
    volumes:
      - opensign-files:/usr/src/app/files
    ports:
      - "8082:8080"  # Host 8082 → Contenedor 8080 (API Server)
    env_file: .env.prod
    environment:
      - NODE_ENV=production
      - SERVER_URL=https://localhost:8082/api/app  # URL de la API
      - PUBLIC_URL=https://localhost:3003          # URL del Front-end
    networks:
      - npm-network

  mongo:
    image: mongo:latest
    container_name: mongo-container
    volumes:
      - data-volume:/data/db
    ports:
      - "27018:27017"  # Host 27018 → Contenedor 27017 (MongoDB)
    networks:
      - npm-network

  client:
    image: opensign/opensign:main
    container_name: OpenSign-container
    depends_on:
      - server
    env_file: .env.prod
    ports:
      - "3003:3000"   # Host 3003 → Contenedor 3000 (Front-end React)
    networks:
      - npm-network

networks:
  npm-network:
    external: true  # La red de Nginx Proxy Manager

volumes:
  data-volume:
  opensign-files:
