services:
  server:
    image: opensign/opensignserver:main
    container_name: OpenSignServer-container
    restart: unless-stopped
    volumes:
      - opensign-files:/usr/src/app/files
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file: .env.prod
    environment:
      - NODE_ENV=production
      - SERVER_URL=${HOST_URL:-https://opensign.rehabilitacion.org.do}/api/app
      - PUBLIC_URL=${HOST_URL:-https://opensign.rehabilitacion.org.do}
      - SMTP_ENABLE=true
      - SMTP_SECURE=false
      - SMTP_HOST=192.168.0.233
      - SMTP_PORT=10025
      - SMTP_USER_EMAIL=opensign@rehabilitacion.org.do      
    networks:
      - npm_network

  mongo:
    image: mongo:latest
    container_name: mongo-container
    restart: unless-stopped
    volumes:
      - data-volume:/data/db
    ports:
      - "27018:27017"
    networks:
      - npm_network

  client:
    image: opensign/opensign:main
    container_name: OpenSign-container
    restart: unless-stopped
    depends_on:
      - server
    env_file: .env.prod  
    ports:
      - "3000:3000"
    networks:
      - npm_network

  caddy:
    image: caddy:latest
    container_name: caddy-container
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - npm_network
    environment:
      - HOST_URL=${HOST_URL:-https://opensign.rehabilitacion.org.do}
      - SMTP_ENABLE=true
      - SMTP_SECURE=false
      - SMTP_HOST=192.168.0.233
      - SMTP_PORT=10025
      - SMTP_USER_EMAIL=opensign@rehabilitacion.org.do

networks:
  npm_network:
    external: true

volumes:
  data-volume:
  web-root:
  caddy_data:
  caddy_config:
  opensign-files:
