version: '3.8'

services:
  server:
    image: opensign/opensignserver:main
    container_name: OpenSignServer-container
    volumes:
      - opensign-files:/usr/src/app/files
    ports:
      - "8082:8080"
    depends_on:
      - mongo
    env_file: .env.prod
    environment:
      - NODE_ENV=production
      - SERVER_URL=${HOST_URL:-https://localhost:3002}/api/app
      - PUBLIC_URL=${HOST_URL:-https://localhost:3002}
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo-container
    volumes:
      - data-volume:/data/db
    ports:
      - "27018:27017"
    networks:
      - app-network

  client:
    image: opensign/opensign:main
    container_name: OpenSign-container
    depends_on:
      - server
    env_file: .env.prod
    # <-- Ya no exponemos 3000 al host; Caddy lo servirá
    networks:
      - app-network

  caddy:
    image: caddy:latest
    container_name: caddy-container
    # Caddy leerá {$HOST_URL} de tu .env.prod (por defecto https://localhost:3002)
    # Y escuchará en el puerto indicado (en este ejemplo, 3002)
    ports:
      - "3002:3002"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    environment:
      - HOST_URL=${HOST_URL:-https://localhost:3002}

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  caddy_data:
  caddy_config:
  opensign-files:
