version: '3.8'

services:
  server:
    image: opensign/opensignserver:main
    container_name: OpenSignServer-container
    volumes:
      - opensign-files:/usr/src/app/files
    ports:
      - "8082:8080"           # Host 8082 → Contenedor 8080 (API)
    depends_on:
      - mongo
    env_file: .env.prod
    environment:
      - NODE_ENV=production
      - SERVER_URL=${HOST_URL:-https://192.168.0.251:3002}/api/app
      - PUBLIC_URL=${HOST_URL:-https://192.168.0.251:3002}
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo-container
    volumes:
      - data-volume:/data/db
    ports:
      - "27018:27017"         # Host 27018 → Contenedor 27017 (MongoDB)
    networks:
      - app-network

  client:
    image: opensign/opensign:main
    container_name: OpenSign-container
    depends_on:
      - server
    env_file: .env.prod
    ports:
      - "3003:3000"           # Host 3003 → Contenedor 3000 (Front-end)
    networks:
      - app-network

  caddy:
    image: caddy:latest
    container_name: caddy-container
    ports:
      - "3002:443"            # Host 3002 → Contenedor 443 (HTTPS)
      # - "3004:80"           # (Opcional) Host 3004 → Contenedor 80 (HTTP)
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    environment:
      - HOST_URL=${HOST_URL:-https://192.168.0.251:3002}

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  caddy_data:
  caddy_config:
  opensign-files:
